steps:
  - name: Checkout Repository
    uses: actions/checkout@v3

  - name: Set up Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18
      cache: 'npm'

  - name: Install Dependencies
    run: npm install

  - name: Run ESLint (CI Only)
    run: npx eslint . --ext .js,.ts || echo "ESLint warnings/errors detected"
