services:
  postgres:
    image: postgres:latest
    env:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    options: >-
      --health-cmd "pg_isready -U postgres"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

  redis:
    image: redis:latest
    ports:
      - 6379:6379

steps:
  - name: Checkout Repository
    uses: actions/checkout@v3

  - name: Set up Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18
      cache: 'npm'

  - name: Install Dependencies
    run: npm install

  - name: Set up Environment Variables
    run: |
      echo "PORT=3000" >> .env
      echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/testdb" >> .env
      echo "REDIS_URL=redis://localhost:6379" >> .env
      echo "OPENEXCHANGE_API_KEY=dummy_key" >> .env
      echo "EXCHANGERATES_API_KEY=dummy_key" >> .env
      echo "FETCH_RATE_INTERVAL=*/5 * * * *" >> .env

  - name: Run Database Migrations
    run: npx sequelize-cli db:migrate

  - name: Run Tests
    run: npm test
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb
      REDIS_URL: redis://localhost:6379